db:
  db_name: fluss_db
  engine: django.db.backends.postgresql
  host: db
  password: c00f399c94e5d1d0e2d53226a4f384cd
  port: 5432
  username: zippyolivebutterfly
django:
  admin:
    email: admin@admin.com
    password: admin
    username: admin
  debug: false
  hosts:
  - '*'
  secret_key: f5)x&h1*l(%36#6bc3vgy88m9q_er)5laiigix6*h233**wfx7
lok:
  issuer: lok
  key_type: RS256
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGFj0zB7j6KrTRFEP+a2Z7toLEwJ0ROF3qSkq6vo2aK5TGRv+D3V/6VhvM2NgtUIO1iqwvf4XETamhHt2xlVzJyoyMAnAGkwkMyQJpI6wG5g7NtrRc1kkeefWbLBVW+aEI++3ec3eD9PUhnjXbQXJwju8l2ldKg2skw2fZWrjfWo0S0CuvB05nXJ8BmmAo65BBv29gGVywzZEApv/Zu16l6ftCZSEKi/zMbK6YxCekl/h3sfK7uGj6uaab7XSqqANHDZDTSotD5ws8UdMb3IP4/qoJiJm0Lsw5XpmFTt9M+ekiv/9HsWjXtzOd0BpqxynlvF1fWDr0HVnrUCh1XMzn
minio:
  access_key: lumpychestnutseahorse
  buckets:
  - name: flussmedia
  host: minio
  port: '9000'
  protocol: http
  secret_key: 828b8c085eccea028878b7a14a18b6d9
redis:
  host: redis
  port: 6379
